apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "irsa-manager.fullname" . }}-manager-role
  labels:
  {{- include "irsa-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - irsa-manager.kkb0318.github.io
  resources:
  - irsas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - irsa-manager.kkb0318.github.io
  resources:
  - irsas/finalizers
  verbs:
  - update
- apiGroups:
  - irsa-manager.kkb0318.github.io
  resources:
  - irsas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - irsa-manager.kkb0318.github.io
  resources:
  - irsasetups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - irsa-manager.kkb0318.github.io
  resources:
  - irsasetups/finalizers
  verbs:
  - update
- apiGroups:
  - irsa-manager.kkb0318.github.io
  resources:
  - irsasetups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "irsa-manager.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: irsa-manager
    app.kubernetes.io/part-of: irsa-manager
  {{- include "irsa-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "irsa-manager.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "irsa-manager.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'